//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CR_CodeTweet.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CR_CodeTweet.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We tried to delete the snippet you posted but couldn&apos;t. Try visiting CodePaste.NET manually to see if you have better luck than us..
        /// </summary>
        internal static string CodePaste_UnableToDeleteSnippet {
            get {
                return ResourceManager.GetString("CodePaste_UnableToDeleteSnippet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfortunately, we can&apos;t establish a session with CodePaste.NET... so we can&apos;t post your snippet..
        /// </summary>
        internal static string CodePaste_UnableToLoginMessage {
            get {
                return ResourceManager.GetString("CodePaste_UnableToLoginMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CodePaste.NET just wasn&apos;t accepting that snippet. Logged in fine but couldn&apos;t post. Weird. Make sure you&apos;re not trying to post a duplicate snippet - CodePaste checks for that..
        /// </summary>
        internal static string CodePaste_UnableToPostSnippet {
            get {
                return ResourceManager.GetString("CodePaste_UnableToPostSnippet", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon ContextButtonIcon {
            get {
                object obj = ResourceManager.GetObject("ContextButtonIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon ContextButtonIconMask {
            get {
                object obj = ResourceManager.GetObject("ContextButtonIconMask", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tweet This!.
        /// </summary>
        internal static string ContextMenu_TweetButton {
            get {
                return ResourceManager.GetString("ContextMenu_TweetButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sends the selected code snippet to CodePaste.NET and tweets a link to the snippet..
        /// </summary>
        internal static string ContextMenu_TweetButtonDescription {
            get {
                return ResourceManager.GetString("ContextMenu_TweetButtonDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For some reason, we couldn&apos;t communicate correctly with Twitter. Try again later. (For details on what happened, check the DevExpress message log.).
        /// </summary>
        internal static string Dialog_GetTwitterPinFailed {
            get {
                return ResourceManager.GetString("Dialog_GetTwitterPinFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We need to send you to Twitter to get a PIN and authorize this app. It&apos;ll ask you to allow/deny the app - click &quot;allow&quot; and then copy the PIN it gives and paste it into the settings here. Are you ready to go?.
        /// </summary>
        internal static string Dialog_GetTwitterPinMessage {
            get {
                return ResourceManager.GetString("Dialog_GetTwitterPinMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve successfully authorized CR_CodeTweet to communicate with Twitter! Awesome!.
        /// </summary>
        internal static string Dialog_GetTwitterPinSuccess {
            get {
                return ResourceManager.GetString("Dialog_GetTwitterPinSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting a Twitter PIN.
        /// </summary>
        internal static string Dialog_GetTwitterPinTitle {
            get {
                return ResourceManager.GetString("Dialog_GetTwitterPinTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The snippet was successfully deleted..
        /// </summary>
        internal static string Dialog_SnippetDeletedMessage {
            get {
                return ResourceManager.GetString("Dialog_SnippetDeletedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snippet deleted!.
        /// </summary>
        internal static string Dialog_SnippetDeletedTitle {
            get {
                return ResourceManager.GetString("Dialog_SnippetDeletedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You canceled the tweet but the snippet got posted. Would you like to delete the snippet?.
        /// </summary>
        internal static string Dialog_TweetCanceledMessage {
            get {
                return ResourceManager.GetString("Dialog_TweetCanceledMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete the snippet?.
        /// </summary>
        internal static string Dialog_TweetCanceledTitle {
            get {
                return ResourceManager.GetString("Dialog_TweetCanceledTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tweet failed but the snippet got posted. Do you want to delete the snippet?.
        /// </summary>
        internal static string Dialog_TweetFailedDeleteSnippetMessage {
            get {
                return ResourceManager.GetString("Dialog_TweetFailedDeleteSnippetMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It doesn&apos;t look like we could post your code snippet and/or get that thing to Twitter..
        /// </summary>
        internal static string Dialog_TweetFailedMessage {
            get {
                return ResourceManager.GetString("Dialog_TweetFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to Post/Tweet.
        /// </summary>
        internal static string Dialog_TweetFailedTitle {
            get {
                return ResourceManager.GetString("Dialog_TweetFailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your snippet was successfully tweeted..
        /// </summary>
        internal static string Dialog_TweetSentMessage {
            get {
                return ResourceManager.GetString("Dialog_TweetSentMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tweet sent!.
        /// </summary>
        internal static string Dialog_TweetSentTitle {
            get {
                return ResourceManager.GetString("Dialog_TweetSentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something happened that we weren&apos;t expecting. We&apos;re gonna have to just bail for now, but you&apos;re free to try again if you want. We put some detail in the DXCore event log, but here&apos;s the short version:.
        /// </summary>
        internal static string Dialog_UnexpectedException {
            get {
                return ResourceManager.GetString("Dialog_UnexpectedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation to post a code snippet and tweet a link failed..
        /// </summary>
        internal static string Exception_TweetFailedMessage {
            get {
                return ResourceManager.GetString("Exception_TweetFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your CodePaste.NET credentials don&apos;t appear to be configured. Please make sure you have specified the username and address with which you log into CodePaste.NET..
        /// </summary>
        internal static string Options_CodePasteNotConfigured {
            get {
                return ResourceManager.GetString("Options_CodePasteNotConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CodeTweet Options Not Configured.
        /// </summary>
        internal static string Options_NotConfiguredTitle {
            get {
                return ResourceManager.GetString("Options_NotConfiguredTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t appear to have authorized CodeTweet to use Twitter. Please make sure you get an OAuth PIN from Twitter and configure CodeTweet. You can get a PIN from the CodeTweet options page..
        /// </summary>
        internal static string Options_TwitterNotConfigured {
            get {
                return ResourceManager.GetString("Options_TwitterNotConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to visit the options page to check your settings?.
        /// </summary>
        internal static string Options_WantToConfigure {
            get {
                return ResourceManager.GetString("Options_WantToConfigure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The flying monkeys are ready to take your code to CodePaste.NET..
        /// </summary>
        internal static string Progress_ConnectedToCodePaste {
            get {
                return ResourceManager.GetString("Progress_ConnectedToCodePaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prepping the flying monkeys for a trip to CodePaste.NET....
        /// </summary>
        internal static string Progress_ConnectingToCodePaste {
            get {
                return ResourceManager.GetString("Progress_ConnectingToCodePaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The monkeys successfully nuked that snippet!.
        /// </summary>
        internal static string Progress_DeletedSnippet {
            get {
                return ResourceManager.GetString("Progress_DeletedSnippet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The monkeys couldn&apos;t nuke your snippet..
        /// </summary>
        internal static string Progress_DeleteSnippetFailed {
            get {
                return ResourceManager.GetString("Progress_DeleteSnippetFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending the monkeys back to CodePaste.NET to delete the snippet....
        /// </summary>
        internal static string Progress_DeletingSnippet {
            get {
                return ResourceManager.GetString("Progress_DeletingSnippet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The monkeys delivered the snippet to CodePaste.NET..
        /// </summary>
        internal static string Progress_PostedSnippet {
            get {
                return ResourceManager.GetString("Progress_PostedSnippet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ninjas posted your tweet!.
        /// </summary>
        internal static string Progress_PostedTweet {
            get {
                return ResourceManager.GetString("Progress_PostedTweet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handing the tweet over to the Twitter ninjas....
        /// </summary>
        internal static string Progress_PostingTweet {
            get {
                return ResourceManager.GetString("Progress_PostingTweet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ninjas refuse to post that tweet. Are they busy fighting a whale?.
        /// </summary>
        internal static string Progress_TweetFailed {
            get {
                return ResourceManager.GetString("Progress_TweetFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CodePaste.NET is denying access to the monkeys....
        /// </summary>
        internal static string Progress_UnableToGetCodePasteSession {
            get {
                return ResourceManager.GetString("Progress_UnableToGetCodePasteSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CodePaste.NET refused the offering of the snippet....
        /// </summary>
        internal static string Progress_UnableToPostSnippet {
            get {
                return ResourceManager.GetString("Progress_UnableToPostSnippet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization with Twitter failed..
        /// </summary>
        internal static string Twitter_AuthorizationFailed {
            get {
                return ResourceManager.GetString("Twitter_AuthorizationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an unexpected error in the Twitter service..
        /// </summary>
        internal static string Twitter_ServerError {
            get {
                return ResourceManager.GetString("Twitter_ServerError", resourceCulture);
            }
        }
    }
}
